### ISSUE TITLE
vendor is not recognized as an internal or external command...

### ISSUE THREAD

**Issue by chilio** [lorisleiva/laravel-deployer#43] opened 2018-08-16 00:13 UTC
I've tried to use your package following hints on [this thread](http://lorisleiva.com/laravel-deployment-using-gitlab-pipelines/)
So, for now, my composer is up to date, but I receive this error while trying to run `php artisan deploy` => 
```
'vendor' is not recognized as an internal or external command,
operable program or batch file.

```
The strange thing is `php artisan deploy:init` didn't produce any errors and I was able to put correct values to the `/config/deploy.php` file.

So my question is what is going wrong here?
Cause I cannot get any hints from this error message.
Btw I have models, classes, etc, with the name `vendor`, but it should not interfere with your package in any way.
I also have missing ssh keys, that's for sure, cause I'm on Win 10 dev and the target system is ubuntu.
But I'm in the middle of creating `.gitlab-ci.yml` script.
I want to set it up for gitlab and being able to deploy...
SSH keys were generated and applied as suggested, but not to my windows dev machine.
Which won't connect obviously for that reason, but anyway error states something different...
So, in the end, I need an answer what does this error mean? 
And how I can resolve this?

**Comment by lorisleiva** [comment] 2018-08-16 07:39
Duplicate of #22

This has been fixed and is now waiting for the next release. Please use `dev-master` until then. Since this is the second duplicate in only a few days, I'm going to tag the next release today.

**Closed by lorisleiva** 2018-08-16 07:39 UTC
