### ISSUE TITLE
Deploying to share hosting not work by  php7.2-fpm reload failed

### ISSUE THREAD

**Issue by reksmeysrey** [lorisleiva/laravel-deployer#128] opened 2019-07-23 16:09 UTC
The command "echo "" | sudo -S /usr/sbin/service php7.2-fpm reload" failed.                                
  Exit Code: 1(General error)             
  Working directory: /home/reksmey/local/project                                                  
  Output:                                                                      
    ================         
  Error Output:                                                                
     ================                                                             
  [sudo] password for linux: Sorry, try again.                               
  [sudo] password for linux:                                                 
  sudo: 1 incorrect password attempt

**Comment by lorisleiva** [comment] 2019-07-24 08:39
Duplicate of #53 and #26

**Closed by lorisleiva** 2019-07-24 08:39 UTC
