### ISSUE TITLE
'vendor' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by shellus** [lorisleiva/laravel-deployer#40] opened 2018-08-13 01:44 UTC
"lorisleiva/laravel-deployer": "^0.2.3",

```cmd
#php artisan deploy:list
>'vendor' is not recognized as an internal or external command,
operable program or batch file.
```
```cmd
#vendor\bin\dep --file='vendor/lorisleiva/laravel-deployer/.build/deploy.php' list
Working properly
```

in windows 10

**Comment by lorisleiva** [comment] 2018-08-13 11:07
Duplicate of #22 

This has been fixed and is now waiting for the next release. Please use `dev-master` until then.

**Closed by lorisleiva** 2018-08-13 11:07 UTC
